# Generated by Django 4.2.5 on 2023-09-23 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('description', models.CharField(max_length=150, verbose_name='Descrição')),
                ('points', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Pontos')),
                ('details', models.CharField(max_length=100, verbose_name='Detalhes')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.campo')),
            ],
        ),
    ]
