# Generated by Django 4.2.5 on 2023-09-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='details',
            field=models.CharField(blank=True, default='Sem detalhes', max_length=100, null=True, verbose_name='Detalhes'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Número'),
        ),
    ]
